[package]
name = "ldap_name_to_cid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ldap3 = "0.11.5"
ureq = { version = "2.10.1", features = ["json"] }
